### ISSUE TITLE
Error at step 5

### ISSUE THREAD

**Issue by mallen6** [maurijlozano/ISCompare#4]
Hi Mauricio, 

ISCompare seems to be working happily but then fails at the stage of writing the final results. Do you have any suggestions how to fix this?

Thanks,
M

I'm using python/3.9.9 with
Biopython/1.79
DNAfeaturesviewer/3.1.0
Pandas/1.3.4
Numpy/1.21.4
Mechanize/0.4.7

My command and the command line output:

> $ ISCompare.py -q R1S1.gbff -r Hlac.gbff -i Hlac_is.fna -o Hlac_v_R1S1_gbff -c -p
> 
>    ********************************************
>    *****   ISCompare
>    *****   Version: 1.0.1
>    *****   Developed by Mauricio J. Lozano
>    *****   github.com/maurijlozano
>    ********************************************
>    Please cite: 
> 
>    Easy identification of insertion sequence mobilization events
>    in related bacterial strains with ISCompare. 
>    E.G. Mogro, N. Ambrosis, M.J. Lozano
>    doi: https://doi.org/10.1101/2020.10.16.342287
>    Instituto de BiotecnologÃ­a y BiologÃ­a Molecular
>    CONICET - CCT La Plata - UNLP - FCE
> 
>    Downloaded from: https://github.com/maurijlozano/ISCompare
> 
> Directory  Hlac_v_R1S1_gbff  created.
> Query: ['R1S1.gbff'] Ref: ['Hlac.gbff']
> Copying files to Hlac_v_R1S1_gbff folder, and extracting fasta files from genbank.
> query.fasta generated.
> ref.fasta generated.
> 133 ISs found on the query genome...
> Step1: Removing identical scaffolds: Query --> Reference ...
> 93 identical scaffolds removed from the analysis...
> Step2: Testing for new IS on the query...
> 123 ISs found on the reference genome...
> Step3: Removing identical scaffolds: Reference --> Query ...
> 0 identical scaffolds removed from the analysis...
> Step4: Testing for IS missing on the query...
> Step5: Consolidating results and annotating data...
> Traceback (most recent call last):
>   File "/apps/iscompare/1.0.1/iscompare/ISCompare.py", line 2297, in <module>
>     FinalResults[['ISstart', 'ISend', 'Start1', 'End1', 'REF.Start1','REF.End1','Start2', 'End2', 'REF.Start2','REF.End2']] = FinalResults[['ISstart', 'ISend', 'Start1', 'End1', 'REF.Start1','REF.End1','Start2', 'End2', 'REF.Start2','REF.End2']].astype("Float32")
>   File "/apps/python/3.9.9/lib/python3.9/site-packages/pandas/core/generic.py", line 5808, in astype
>     results = [
>   File "/apps/python/3.9.9/lib/python3.9/site-packages/pandas/core/generic.py", line 5809, in <listcomp>
>     self.iloc[:, i].astype(dtype, copy=copy)
>   File "/apps/python/3.9.9/lib/python3.9/site-packages/pandas/core/generic.py", line 5815, in astype
>     new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
>   File "/apps/python/3.9.9/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 418, in astype
>     return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
>   File "/apps/python/3.9.9/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 327, in apply
>     applied = getattr(b, f)(**kwargs)
>   File "/apps/python/3.9.9/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 591, in astype
>     new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
>   File "/apps/python/3.9.9/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 1309, in astype_array_safe
>     new_values = astype_array(values, dtype, copy=copy)
>   File "/apps/python/3.9.9/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 1257, in astype_array
>     values = astype_nansafe(values, dtype, copy=copy)
>   File "/apps/python/3.9.9/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 1105, in astype_nansafe
>     return dtype.construct_array_type()._from_sequence(arr, dtype=dtype, copy=copy)
>   File "/apps/python/3.9.9/lib/python3.9/site-packages/pandas/core/arrays/floating.py", line 261, in _from_sequence
>     values, mask = coerce_to_array(scalars, dtype=dtype, copy=copy)
>   File "/apps/python/3.9.9/lib/python3.9/site-packages/pandas/core/arrays/floating.py", line 143, in coerce_to_array
>     raise TypeError(f"{values.dtype} cannot be converted to a FloatingDtype")
> TypeError: object cannot be converted to a FloatingDtype
>

**Comment by maurijlozano** [comment]
Hi mallen6, the error was already corrected, but I forgot to make a new release of the code. 
Please try with version 1.0.3
https://github.com/maurijlozano/ISCompare/releases/tag/1.0.3
Thank's for reporting the bugs.
